<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>9</LangVersion>
        <Nullable>enable</Nullable>
        <Version>0.1.1</Version>
        <Title>Omnihavior</Title>
        <Authors>Aleksandras Terechovas(Aleksandr Terekhov)</Authors>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\Omnihavior.Unity\Runtime\Builder.cs">
            <Link>Builder.cs</Link>
        </Compile>
        <Compile Include="..\Omnihavior.Unity\Runtime\Core\**\*.cs">
            <Link>Core\**</Link>
        </Compile>
        <Compile Include="..\Omnihavior.Unity\Runtime\States\**\*.cs">
            <Link>States\**</Link>
        </Compile>
        <Compile Include="..\Omnihavior.Unity\Runtime\Utility\**\*.cs">
            <Link>Utility\**</Link>
        </Compile>
        <Compile Include="..\Omnihavior.Unity\Runtime\Trees\**\*.cs">
            <Link>Trees\**</Link>
        </Compile>
        <Compile Include="..\Omnihavior.Unity\Runtime\Goals\**\*.cs">
            <Link>Goals\**</Link>
        </Compile>
    </ItemGroup>

</Project>
